### ISSUE TITLE
KeyError: action__path

### ISSUE THREAD

**Issue by petobens** [raghur/fruzzy#13]
Consider the following minimal vimrc:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/raghur/fruzzy
filetype plugin indent on


let g:fruzzy#usenative = 0
call denite#custom#source('_', 'matchers', ['matcher/fruzzy',
        \ 'matcher/ignore_globs'])
```
Now open vim/nvim and run `:Denite  command`. I get the following error:
```
[denite] Traceback (most recent call last):
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 121, in _start
[denite]     self.update_candidates()
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/ui/default.py", line 312, in update_candidates
[denite]     self._denite.filter_candidates(self._context)):
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 120, in filter_candidates
[denite]     self.match_candidates(ctx, matchers)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 159, in match_candidates
[denite]     context['candidates'] = self.call_matchers(ctx, matchers)
[denite]   File "/home/pedro/git-repos/private/dotfiles/vim/bundle/.cache/init.vim/.dein/rplugin/python3/denite/denite.py", line 163, in call_matchers
[denite]     ctx['candidates'] = matcher.filter(ctx)
[denite]   File "/home/pedro/.config/nvim/bundle/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/filter/matcher/ignore_globs.py", line 42, in filter
[denite]     return [x for x in context['candidates']
[denite]   File "/home/pedro/.config/nvim/bundle/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/filter/matcher/ignore_globs.py", line 43, in <listcomp>
[denite]     if not search(pattern, x['action__path'][:max_width])]
[denite] KeyError: 'action__path'
[denite] Please execute :messages command.
```
Maybe it's something with recen updates with Denite @Shougo? Thanks

**Comment by Shougo** [comment]
It is not fruzzy issue.  It is denite.nvim issue.
I will fix it later.

**Comment by petobens** [comment]
@Shougo do you want me to open an issue in the denite repo?

**Comment by Shougo** [comment]
I have fixed the error in denite.nvim.
Please update it.
